#!/bin/sh
#
# BusyBox / SysV style init script for aesdsocket
# Uses start-stop-daemon so we don’t have to reinvent daemonisation.
#
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 5        # multi-user targets
# Default-Stop:      0 1 2 6
# Short-Description: TCP 9000 echo-append service
### END INIT INFO

DAEMON=/usr/bin/aesdsocket          # installed by Buildroot
DAEMON_OPTS="-d"                    # our own double-fork code
PIDFILE=/var/run/aesdsocket.pid
NAME=aesdsocket

start() {
        printf "Starting %s: " "$NAME"
        start-stop-daemon -S -b -m \
                -p "$PIDFILE" \
                --exec "$DAEMON" -- $DAEMON_OPTS
        echo "OK"
}

stop() {
        printf "Stopping %s: " "$NAME"
        start-stop-daemon -K -p "$PIDFILE" --signal TERM
        rm -f "$PIDFILE"
        echo "OK"
}

case "$1" in
        start)   start   ;;
        stop)    stop    ;;
        restart) stop ; start ;;
        status)  start-stop-daemon -K -t -p "$PIDFILE" && echo "running" || echo "stopped" ;;
        *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac

exit 0

